export const CREATE_ABILITIES = 'CREATE_ABILITIES';
export const CREATE_AFFINITIES = 'CREATE_AFFINITIES';
export const CREATE_UNITS = 'CREATE_UNITS';
export const CREATE_RATED_UNITS = 'CREATE_RATED_UNITS';
export const CREATE_SPONSOR_AFFINITY_GROUP_AVAILABILITIES = 'CREATE_SPONSOR_AFFINITY_GROUP_AVAILABILITIES';
