export const CREATE_ABILITIES = 'CREATE_ABILITIES';
export const CREATE_AFFINITIES = 'CREATE_AFFINITIES';
export const CREATE_PLAYERS = 'CREATE_PLAYERS';
export const CREATE_RATED_PLAYERS = 'CREATE_RATED_PLAYERS';

export const REQUEST_PLAYERS = 'REQUEST_PLAYERS';
export const FETCHING_PLAYERS = 'FETCHING_PLAYERS';
export const REQUEST_SUCCESS_PLAYERS = 'REQUEST_SUCCESS_PLAYERS';
export const CHANGE_PAGE_NEXT_PLAYERS = 'CHANGE_PAGE_NEXT_PLAYERS';
export const CHANGE_PAGE_PREV_PLAYERS = 'CHANGE_PAGE_PREV_PLAYERS';

export const REQUEST_TEAM_PLAYERS = 'REQUEST_TEAM_PLAYERS';
export const FETCHING_TEAM_PLAYERS = 'FETCHING_TEAM_PLAYERS';
export const REQUEST_SUCCESS_TEAM_PLAYERS = 'REQUEST_SUCCESS_TEAM_PLAYERS';
export const CHANGE_PAGE_NEXT_TEAM_PLAYERS = 'CHANGE_PAGE_NEXT_TEAM_PLAYERS';
export const CHANGE_PAGE_PREV_TEAM_PLAYERS = 'CHANGE_PAGE_PREV_TEAM_PLAYERS';
