export const CREATE_ABILITIES = 'CREATE_ABILITIES';
export const CREATE_AFFINITIES = 'CREATE_AFFINITIES';
export const CREATE_UNITS = 'CREATE_UNITS';
export const CREATE_RATED_UNITS = 'CREATE_RATED_UNITS';
export const CREATE_SPONSOR_AFFINITY_GROUP_AVAILABILITIES = 'CREATE_SPONSOR_AFFINITY_GROUP_AVAILABILITIES';

export const REQUEST_UNITS = 'REQUEST_UNITS';
export const REQUEST_SUCCESS_UNITS = 'REQUEST_SUCCESS_UNITS';
export const CHANGE_PAGE_NEXT_UNITS = 'CHANGE_PAGE_NEXT_UNITS';
export const CHANGE_PAGE_PREV_UNITS = 'CHANGE_PAGE_PREV_UNITS';

export const REQUEST_SPONSOR_UNITS = 'REQUEST_SPONSOR_UNITS';
export const REQUEST_SUCCESS_SPONSOR_UNITS = 'REQUEST_SUCCESS_SPONSOR_UNITS';
export const CHANGE_PAGE_NEXT_SPONSOR_UNITS = 'CHANGE_PAGE_NEXT_SPONSOR_UNITS';
export const CHANGE_PAGE_PREV_SPONSOR_UNITS = 'CHANGE_PAGE_PREV_SPONSOR_UNITS';

export const REQUEST_SPONSOR_AFFINITY_GROUP_AVAILABILITIES = 'REQUEST_SPONSOR_AFFINITY_GROUP_AVAILABILITIES';
export const REQUEST_SUCCESS_SPONSOR_AFFINITY_GROUP_AVAILABILITIES = 'REQUEST_SUCCESS_SPONSOR_AFFINITY_GROUP_AVAILABILITIES';
