export const REQUEST_SPONSOR_AFFINITY_GROUP_AVAILABILITIES = 'REQUEST_SPONSOR_AFFINITY_GROUP_AVAILABILITIES';
export const REQUEST_SPONSOR_AFFINITY_GROUP_AVAILABILITIES_SUCCESS = 'REQUEST_SPONSOR_AFFINITY_GROUP_AVAILABILITIES_SUCCESS';
export const REQUEST_SPONSOR_AFFINITY_GROUP_AVAILABILITIES_FAILURE = 'REQUEST_SPONSOR_AFFINITY_GROUP_AVAILABILITIES_FAILURE';

export const REQUEST_UNITS = 'REQUEST_UNITS';
export const REQUEST_UNITS_SUCCESS = 'REQUEST_UNITS_SUCCESS';
export const REQUEST_UNITS_FAILURE = 'REQUEST_UNITS_FAILURE';

export const REQUEST_SPONSOR_UNITS = 'REQUEST_SPONSOR_UNITS';
export const REQUEST_SPONSOR_UNITS_SUCCESS = 'REQUEST_SPONSOR_UNITS_SUCCESS';
export const REQUEST_SPONSOR_UNITS_FAILURE = 'REQUEST_SPONSOR_UNITS_FAILURE';

export const CREATE_ABILITIES = 'CREATE_ABILITIES';
export const CREATE_AFFINITIES = 'CREATE_AFFINITIES';
export const CREATE_UNITS = 'CREATE_UNITS';
export const CREATE_RATED_UNITS = 'CREATE_UNITS';
export const CREATE_SPONSOR_AFFINITY_GROUP_AVAILABILITIES = 'CREATE_SPONSOR_AFFINITY_GROUP_AVAILABILITIES';
