export const REQUEST_SPONSOR_AFFINITY_GROUP_AVAILABILITIES = 'REQUEST_SPONSOR_AFFINITY_GROUP_AVAILABILITIES';
export const REQUEST_SPONSOR_AFFINITY_GROUP_AVAILABILITIES_SUCCESS = 'REQUEST_SPONSOR_AFFINITY_GROUP_AVAILABILITIES_SUCCESS';
export const REQUEST_SPONSOR_AFFINITY_GROUP_AVAILABILITIES_FAILURE = 'REQUEST_SPONSOR_AFFINITY_GROUP_AVAILABILITIES_FAILURE';

export const REQUEST_UNITS = 'REQUEST_UNITS';
export const REQUEST_UNITS_SUCCESS = 'REQUEST_UNITS_SUCCESS';
export const REQUEST_UNITS_FAILURE = 'REQUEST_UNITS_FAILURE';

export const REQUEST_SPONSOR_UNITS = 'REQUEST_SPONSOR_UNITS';
export const REQUEST_SPONSOR_UNITS_SUCCESS = 'REQUEST_SPONSOR_UNITS_SUCCESS';
export const REQUEST_SPONSOR_UNITS_FAILURE = 'REQUEST_SPONSOR_UNITS_FAILURE';
