# Travis CI Configuration file
# @link https://travis-ci.org/

# Using Java for the project
language: java
jdk:
# JDK 8 is set to deploy the docs and artifacts
  - oraclejdk8
env:
  - DEPLOY=true
  - DEPLOY_DOCS=true

before_install:
  # Scripts are set as executable
  - chmod +x ./.scripts/load-travis-environment.sh
  - chmod +x ./.scripts/create-maven-settings.sh
  - chmod +x ./.scripts/deploy-site.sh
  # Prepares CI environment
  - source ./.scripts/load-travis-environment.sh
  # Creates Maven settings
  - ./.scripts/create-maven-settings.sh
script:
  # Unit and integration tests are run
  - mvn clean verify -P h2
after_success:
  # Documentation deployment script
  - ./.scripts/deploy-site.sh
