export const CHOOSE_SPONSOR_AFFINITY = 'CHOOSE_SPONSOR_AFFINITY';

export const TEAM_AFFINITIES_VALIDATION = 'TEAM_AFFINITIES_VALIDATION';

export const REQUEST_SUCCESS_TEAM_VALIDATION_AFFINITIES = 'REQUEST_SUCCESS_TEAM_VALIDATION_AFFINITIES';
