export const CHOOSE_SPONSOR_AFFINITY = 'CHOOSE_SPONSOR_AFFINITY';

export const TEAM_AFFINITIES_VALIDATION = 'TEAM_AFFINITIES_VALIDATION';

export const SET_AFFINITY_OPTIONS = 'SET_AFFINITY_OPTIONS';

export const SET_CHOSEN_AFFINITIES = 'SET_CHOSEN_AFFINITIES';
