export const CHOOSE_SPONSOR_AFFINITY = 'CHOOSE_SPONSOR_AFFINITY';

export const TEAM_AFFINITIES_VALIDATION = 'TEAM_AFFINITIES_VALIDATION';

export const SET_AFFINITY_OPTIONS = 'SET_AFFINITY_OPTIONS';

export const SET_CHOSEN_AFFINITIES = 'SET_CHOSEN_AFFINITIES';

export const REQUEST_SUCCESS_TEAM_VALIDATION_AFFINITIES = 'REQUEST_SUCCESS_TEAM_VALIDATION_AFFINITIES';
export const REQUEST_FAILURE_TEAM_VALIDATION_AFFINITIES = 'REQUEST_FAILURE_TEAM_VALIDATION_AFFINITIES';
