export const CREATE_ABILITIES = 'CREATE_ABILITIES';
export const CREATE_AFFINITIES = 'CREATE_AFFINITIES';
export const CREATE_PLAYERS = 'CREATE_PLAYERS';
export const CREATE_RATED_PLAYERS = 'CREATE_RATED_PLAYERS';

export const REQUEST_PLAYERS = 'REQUEST_PLAYERS';
export const FETCHING_PLAYERS = 'FETCHING_PLAYERS';

export const REQUEST_SUCCESS_PLAYERS = 'REQUEST_SUCCESS_PLAYERS';
export const REQUEST_FAILURE_PLAYERS = 'REQUEST_FAILURE_PLAYERS';

export const CHANGE_PAGE_NEXT_PLAYERS = 'CHANGE_PAGE_NEXT_PLAYERS';
export const CHANGE_PAGE_PREV_PLAYERS = 'CHANGE_PAGE_PREV_PLAYERS';

export const REQUEST_RATED_PLAYERS = 'REQUEST_RATED_PLAYERS';
export const FETCHING_RATED_PLAYERS = 'FETCHING_RATED_PLAYERS';

export const REQUEST_SUCCESS_RATED_PLAYERS = 'REQUEST_SUCCESS_RATED_PLAYERS';
export const REQUEST_FAILURE_RATED_PLAYERS = 'REQUEST_FAILURE_RATED_PLAYERS';

export const CHANGE_PAGE_NEXT_RATED_PLAYERS = 'CHANGE_PAGE_NEXT_RATED_PLAYERS';
export const CHANGE_PAGE_PREV_RATED_PLAYERS = 'CHANGE_PAGE_PREV_RATED_PLAYERS';
