export const REQUEST_RATED_PLAYERS = 'REQUEST_RATED_PLAYERS';
export const FETCHING_RATED_PLAYERS = 'FETCHING_RATED_PLAYERS';

export const REQUEST_SUCCESS_RATED_PLAYERS = 'REQUEST_SUCCESS_RATED_PLAYERS';
export const REQUEST_FAILURE_RATED_PLAYERS = 'REQUEST_FAILURE_RATED_PLAYERS';

export const CHANGE_PAGE_NEXT_RATED_PLAYERS = 'CHANGE_PAGE_NEXT_RATED_PLAYERS';
export const CHANGE_PAGE_PREV_RATED_PLAYERS = 'CHANGE_PAGE_PREV_RATED_PLAYERS';
