export const FETCH_AFFINITY_GROUPS_REQUEST = 'FETCH_AFFINITIES_REQUEST'
export const FETCH_AFFINITY_GROUPS_FAILURE = 'FETCH_AFFINITIES_FAILURE'
export const FETCH_AFFINITY_GROUPS_SUCCESS = 'FETCH_AFFINITIES_SUCCESS'

export const FETCH_UNITS_REQUEST = 'FETCH_UNITS_REQUEST'
export const FETCH_UNITS_FAILURE = 'FETCH_UNITS_FAILURE'
export const FETCH_UNITS_SUCCESS = 'FETCH_UNITS_SUCCESS'

export const REQUEST_AFFINITY_GROUPS = 'REQUEST_AFFINITIES'
export const RECEIVE_AFFINITY_GROUPS = 'RECEIVE_AFFINITIES'

export const REQUEST_UNITS = 'REQUEST_UNITS'
export const RECEIVE_UNITS = 'RECEIVE_UNITS'

