export const FETCH_UNITS_REQUEST = 'FETCH_UNITS_REQUEST'
export const FETCH_UNITS_FAILURE = 'FETCH_UNITS_FAILURE'
export const FETCH_UNITS_SUCCESS = 'FETCH_UNITS_SUCCESS'

export const LOAD_UNITS = 'LOAD_UNITS'

export const REQUEST_UNITS = 'REQUEST_UNITS'
export const RECEIVE_UNITS = 'RECEIVE_UNITS'
