export const TOGGLE_NAV_BAR = 'TOGGLE_NAV_BAR';

export const HIDE_NAV_ON_SMALL_SCREEN = 'HIDE_NAV_ON_SMALL_SCREEN';

export const SET_NAV_BAR_VISIBLE_STATUS = 'SET_NAV_BAR_VISIBLE_STATUS';
export const SET_SMALL_SCREEN_STATUS = 'SET_SMALL_SCREEN_STATUS';
