export const TOGGLE_SIDE_BAR = 'TOGGLE_SIDE_BAR';
export const TOGGLE_NAV_BAR = 'TOGGLE_NAV_BAR';

export const HIDE_NAV_ON_SMALL_SCREEN = 'HIDE_NAV_ON_SMALL_SCREEN';
export const HIDE_SIDE_ON_SMALL_SCREEN = 'HIDE_SIDE_ON_SMALL_SCREEN';

export const SET_SMALL_SCREEN_STATUS = 'SET_SMALL_SCREEN_STATUS';
