export const BEGIN_DBX_TEAM_BUILDING = 'BEGIN_DBX_TEAM_BUILDING';

export const CHOOSE_SPONSOR_AFFINITY = 'CHOOSE_SPONSOR_AFFINITY';

export const ADD_TEAM_UNIT = 'ADD_TEAM_UNIT';
export const REMOVE_TEAM_UNIT = 'REMOVE_TEAM_UNIT';

export const SET_SPONSOR_NAME = 'SET_SPONSOR_NAME';

export const TEAM_VALIDATION = 'TEAM_VALIDATION';
export const TEAM_AFFINITIES_VALIDATION = 'TEAM_AFFINITIES_VALIDATION';

export const SET_BASE_RANK = 'SET_BASE_RANK';
export const SET_RANK = 'SET_RANK';
export const SET_TEAM_VALUE = 'SET_TEAM_VALUE';
export const SET_TEAM_UNITS = 'SET_TEAM_UNITS';

export const SET_SPONSOR_CHEERLEADERS = 'SET_SPONSOR_CHEERLEADERS';
export const SET_SPONSOR_COACHING_DICE = 'SET_SPONSOR_COACHING_DICE';
export const SET_SPONSOR_MEDIBOT = 'SET_SPONSOR_MEDIBOT';
export const SET_SPONSOR_NASTY_SURPRISE_CARD = 'SET_SPONSOR_NASTY_SURPRISE_CARD';
export const SET_SPONSOR_SPECIAL_MOVE_CARD = 'SET_SPONSOR_SPECIAL_MOVE_CARD';
export const SET_SPONSOR_WAGER = 'SET_SPONSOR_WAGER';

export const REQUEST_SUCCESS_SPONSOR_TEAM_VALIDATION = 'REQUEST_SUCCESS_SPONSOR_TEAM_VALIDATION';
export const REQUEST_SUCCESS_SPONSOR_TEAM_VALIDATION_AFFINITIES = 'REQUEST_SUCCESS_SPONSOR_TEAM_VALIDATION_AFFINITIES';
