export const BEGIN_DBX_TEAM_BUILDING = 'BEGIN_DBX_TEAM_BUILDING';

export const CHOOSE_SPONSOR_AFFINITY = 'CHOOSE_SPONSOR_AFFINITY';
export const CHOOSE_SPONSOR_UNIT = 'CHOOSE_SPONSOR_UNIT';

export const RELOAD_SPONSOR_RANK = 'RELOAD_SPONSOR_RANK';
export const RELOAD_SPONSOR_TEAM_VALUE = 'RELOAD_SPONSOR_TEAM_VALUE';

export const UPDATE_SPONSOR_CHEERLEADERS = 'UPDATE_SPONSOR_CHEERLEADERS';
export const UPDATE_SPONSOR_COACHING_DICE = 'UPDATE_SPONSOR_COACHING_DICE';
export const UPDATE_SPONSOR_MEDIBOT = 'UPDATE_SPONSOR_MEDIBOT';
export const UPDATE_SPONSOR_NASTY_SURPRISE_CARD = 'UPDATE_SPONSOR_NASTY_SURPRISE_CARD';
export const UPDATE_SPONSOR_SPECIAL_MOVE_CARD = 'UPDATE_SPONSOR_SPECIAL_MOVE_CARD';
export const UPDATE_SPONSOR_WAGER = 'UPDATE_SPONSOR_WAGER';

export const REQUEST_BUILDER_DEFAULTS = 'REQUEST_BUILDER_DEFAULTS';
export const REQUEST_BUILDER_DEFAULTS_SUCCESS = 'REQUEST_BUILDER_DEFAULTS_SUCCESS';
export const REQUEST_BUILDER_DEFAULTS_FAILURE = 'REQUEST_BUILDER_DEFAULTS_FAILURE';
