export const BEGIN_DBX_TEAM_BUILDING = 'BEGIN_DBX_TEAM_BUILDING';

export const CHOOSE_SPONSOR_AFFINITY = 'CHOOSE_SPONSOR_AFFINITY';
export const CHOOSE_SPONSOR_UNIT = 'CHOOSE_SPONSOR_UNIT';

export const UPDATE_SPONSOR_NAME = 'UPDATE_SPONSOR_NAME';

export const SET_BASE_RANK = 'SET_BASE_RANK';
export const SET_RANK = 'SET_RANK';
export const SET_TEAM_VALUE = 'SET_TEAM_VALUE';
export const SET_SPONSOR_UNITS = 'SET_SPONSOR_UNITS';

export const UPDATE_SPONSOR_CHEERLEADERS = 'UPDATE_SPONSOR_CHEERLEADERS';
export const UPDATE_SPONSOR_COACHING_DICE = 'UPDATE_SPONSOR_COACHING_DICE';
export const UPDATE_SPONSOR_MEDIBOT = 'UPDATE_SPONSOR_MEDIBOT';
export const UPDATE_SPONSOR_NASTY_SURPRISE_CARD = 'UPDATE_SPONSOR_NASTY_SURPRISE_CARD';
export const UPDATE_SPONSOR_SPECIAL_MOVE_CARD = 'UPDATE_SPONSOR_SPECIAL_MOVE_CARD';
export const UPDATE_SPONSOR_WAGER = 'UPDATE_SPONSOR_WAGER';

export const REQUEST_SPONSOR_TEAM_VALIDATION = 'REQUEST_SPONSOR_TEAM_VALIDATION';
export const REQUEST_SPONSOR_TEAM_VALIDATION_SUCCESS = 'REQUEST_SPONSOR_TEAM_VALIDATION_SUCCESS';
export const REQUEST_SPONSOR_TEAM_VALIDATION_FAILURE = 'REQUEST_SPONSOR_TEAM_VALIDATION_FAILURE';

export const REQUEST_SPONSOR_TEAM_VALIDATION_AFFINITIES = 'REQUEST_SPONSOR_TEAM_VALIDATION_AFFINITIES';
export const REQUEST_SPONSOR_TEAM_VALIDATION_AFFINITIES_SUCCESS = 'REQUEST_SPONSOR_TEAM_VALIDATION_AFFINITIES_SUCCESS';
export const REQUEST_SPONSOR_TEAM_VALIDATION_AFFINITIES_FAILURE = 'REQUEST_SPONSOR_TEAM_VALIDATION_AFFINITIES_FAILURE';
