export const REQUEST_SPONSOR_AFFINITY_GROUP_AVAILABILITIES = 'REQUEST_SPONSOR_AFFINITY_GROUP_AVAILABILITIES'
export const REQUEST_SPONSOR_AFFINITY_GROUP_AVAILABILITIES_SUCCESS = 'REQUEST_SPONSOR_AFFINITY_GROUP_AVAILABILITIES_SUCCESS'
export const REQUEST_SPONSOR_AFFINITY_GROUP_AVAILABILITIES_FAILURE = 'REQUEST_SPONSOR_AFFINITY_GROUP_AVAILABILITIES_FAILURE'

export const FETCH_UNITS_REQUEST = 'FETCH_UNITS_REQUEST'
export const FETCH_UNITS_FAILURE = 'FETCH_UNITS_FAILURE'
export const FETCH_UNITS_SUCCESS = 'FETCH_UNITS_SUCCESS'

export const RECEIVE_SPONSOR_AFFINITY_GROUP_AVAILABILITIES = 'RECEIVE_SPONSOR_AFFINITY_GROUP_AVAILABILITIES'

export const REQUEST_UNITS = 'REQUEST_UNITS'
export const REQUEST_UNITS_SUCCESS = 'REQUEST_UNITS_SUCCESS'
export const REQUEST_UNITS_FAILURE = 'REQUEST_UNITS_FAILURE'

export const BEGIN_DBX_TEAM_BUILDING = 'BEGIN_DBX_TEAM_BUILDING'

export const CHOOSE_SPONSOR_AFFINITY = 'CHOOSE_SPONSOR_AFFINITY'

export const CALL_API = 'Call API'
